- #### 로또 번호 자동 생성기를 함수를 이용해 만드시오.

In [8]:
import numpy as np

In [9]:
def lotto():
    return np.random.choice(np.arange(1, 46), size = 6, replace = False)

In [11]:
lotto()

array([34,  4,  8, 41, 38, 33])

- #### $x > 30$ 인 원소 필터링

In [13]:
x = np.random.randint(1, 100, size=10)
print(x)

[80 44 88 92 36 97  4 36 50 75]


In [14]:
print(x)

[80 44 88 92 36 97  4 36 50 75]


In [16]:
x > 30

array([ True,  True,  True,  True,  True,  True, False,  True,  True,
        True])

In [15]:
x[x > 30]

array([80, 44, 88, 92, 36, 97, 36, 50, 75])

- #### 짝수이고, $x < 50$ 인 원소 필터링

In [17]:
x % 2 == 0

array([ True,  True,  True,  True,  True, False,  True,  True,  True,
       False])

In [18]:
x < 50

array([False,  True, False, False,  True, False,  True,  True, False,
       False])

In [21]:
x[(x % 2 == 0) & (x < 50)]

array([44, 36,  4, 36])

- #### $x < 50$ 이거나 $x > 80$인 원소 필터링

In [22]:
x < 50

array([False,  True, False, False,  True, False,  True,  True, False,
       False])

In [23]:
x > 80

array([False, False,  True,  True, False,  True, False, False, False,
       False])

In [24]:
x[(x < 50) | (x > 80)]

array([44, 88, 92, 36, 97,  4, 36])

- #### redwine 의 변수(열, column)별 평균값을 구하시오.

In [25]:
redwine = np.loadtxt(fname="wine_red.csv", delimiter=";", skiprows=1)
print(redwine)

[[ 3.51  9.4   5.  ]
 [ 3.2   9.8   5.  ]
 [ 3.26  9.8   5.  ]
 [ 3.16  9.8   6.  ]
 [ 3.51  9.4   5.  ]
 [ 3.51  9.4   5.  ]
 [ 3.3   9.4   5.  ]
 [ 3.39 10.    7.  ]
 [ 3.36  9.5   7.  ]
 [ 3.35 10.5   5.  ]
 [ 3.28  9.2   5.  ]
 [ 3.35 10.5   5.  ]
 [ 3.58  9.9   5.  ]
 [ 3.26  9.1   5.  ]
 [ 3.16  9.2   5.  ]
 [ 3.17  9.2   5.  ]
 [ 3.3  10.5   7.  ]
 [ 3.11  9.3   5.  ]
 [ 3.38  9.    4.  ]
 [ 3.04  9.2   6.  ]
 [ 3.39  9.4   6.  ]
 [ 3.52  9.7   5.  ]
 [ 3.17  9.5   5.  ]
 [ 3.17  9.4   5.  ]
 [ 3.43  9.7   6.  ]
 [ 3.34  9.3   5.  ]
 [ 3.28  9.5   5.  ]
 [ 3.17  9.5   5.  ]
 [ 3.47  9.4   5.  ]
 [ 3.38  9.8   6.  ]
 [ 3.35 10.1   5.  ]
 [ 3.46 10.6   6.  ]
 [ 3.17  9.8   5.  ]
 [ 3.45  9.4   6.  ]
 [ 3.38  9.2   5.  ]
 [ 3.4   9.6   6.  ]
 [ 3.42 10.8   6.  ]
 [ 3.23  9.7   7.  ]
 [ 3.5   9.8   4.  ]
 [ 3.33 10.5   5.  ]
 [ 3.33 10.5   5.  ]
 [ 3.26  9.3   4.  ]
 [ 3.21 10.5   6.  ]
 [ 3.3  10.3   5.  ]
 [ 3.48  9.5   5.  ]
 [ 3.9  13.1   4.  ]
 [ 3.25  9.2   5.  ]
 [ 3.25  9.5 

In [26]:
redwine.sum(axis=0)

array([333.34, 978.3 , 525.  ])

In [29]:
len(redwine)

100

In [30]:
print(redwine.mean(axis=0))

[3.3334 9.783  5.25  ]


- #### redwine 의 alcohol 평균값만 구하시오.

In [31]:
print(redwine[:,1].mean())

9.783000000000001


In [32]:
len(redwine)

100

- #### alcohol이 9.5 이상인 와인은 몇 개인지 구하시오.

In [34]:
len(redwine[redwine[:, 1] >= 9.5])

62

- #### alcohol이 9.5 이상인 와인의 평균 alchol 값은 얼마인지 구하시오.

In [43]:
redwine[redwine[:,1] >=9.5][:, 1].mean()

10.1