### LSTM 문장생성하기
- https://www.kaggle.com/aashita/nyt-comments
- ArticlesApril2018.csv

In [3]:
import pandas as pd
df=pd.read_csv('ArticlesApril2018.csv')
df.head()

articleID  articleWordCount  \
0  5adf6684068401528a2aa69b               781   
1  5adf653f068401528a2aa697               656   
2  5adf4626068401528a2aa628              2427   
3  5adf40d2068401528a2aa619               626   
4  5adf3d64068401528a2aa60f               815   

                                      byline documentType  \
0                             By JOHN BRANCH      article   
1                           By LISA FRIEDMAN      article   
2                              By PETE WELLS      article   
3  By JULIE HIRSCHFELD DAVIS and PETER BAKER      article   
4             By IAN AUSTEN and DAN BILEFSKY      article   

                                            headline  \
0  Former N.F.L. Cheerleaders’ Settlement Offer: ...   
1  E.P.A. to Unveil a New Rule. Its Effect: Less ...   
2                            The New Noma, Explained   
3                                            Unknown   
4                                            Unknown   

                                            keywords  multimedia     newDesk  \
0  ['Workplace Hazards and Violations', 'Football...          68      Sports   
1  ['Environmental Protection Agency', 'Pruitt, S...          68     Climate   
2  ['Restaurants', 'Noma (Copenhagen, Restaurant)...          66      Dining   
3  ['Macron, Emmanuel (1977- )', 'Trump, Donald J...          68  Washington   
4  ['Toronto, Ontario, Attack (April, 2018)', 'Mu...          68     Foreign   

   printPage              pubDate   sectionName  \
0          0  2018-04-24 17:16:49  Pro Football   
1          0  2018-04-24 17:11:21       Unknown   
2          0  2018-04-24 14:58:44       Unknown   
3          0  2018-04-24 14:35:57        Europe   
4          0  2018-04-24 14:21:21        Canada   

                                             snippet              source  \
0  “I understand that they could meet with us, pa...  The New York Times   
1  The agency plans to publish a new regulation T...  The New York Times   
2  What’s it like to eat at the second incarnatio...  The New York Times   
3  President Trump welcomed President Emmanuel Ma...  The New York Times   
4  Alek Minassian, 25, a resident of Toronto’s Ri...  The New York Times   

  typeOfMaterial                                             webURL  
0           News  https://www.nytimes.com/2018/04/24/sports/foot...  
1           News  https://www.nytimes.com/2018/04/24/climate/epa...  
2           News  https://www.nytimes.com/2018/04/24/dining/noma...  
3           News  https://www.nytimes.com/2018/04/24/world/europ...  
4           News  https://www.nytimes.com/2018/04/24/world/canad...

In [6]:
print(df.columns)
print(len(df.columns))

Index(['articleID', 'articleWordCount', 'byline', 'documentType', 'headline',
       'keywords', 'multimedia', 'newDesk', 'printPage', 'pubDate',
       'sectionName', 'snippet', 'source', 'typeOfMaterial', 'webURL'],
      dtype='object')
15


In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1324 entries, 0 to 1323
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   articleID         1324 non-null   object
 1   articleWordCount  1324 non-null   int64 
 2   byline            1324 non-null   object
 3   documentType      1324 non-null   object
 4   headline          1324 non-null   object
 5   keywords          1324 non-null   object
 6   multimedia        1324 non-null   int64 
 7   newDesk           1324 non-null   object
 8   printPage         1324 non-null   int64 
 9   pubDate           1324 non-null   object
 10  sectionName       1324 non-null   object
 11  snippet           1324 non-null   object
 12  source            1324 non-null   object
 13  typeOfMaterial    1324 non-null   object
 14  webURL            1324 non-null   object
dtypes: int64(3), object(12)
memory usage: 155.3+ KB


In [8]:
df['headline'].isnull().values.any()

False

In [10]:
headline=[]
headline.extend(list(df.headline.values))
headline[:5]

['Former N.F.L. Cheerleaders’ Settlement Offer: $1 and a Meeting With Goodell',
 'E.P.A. to Unveil a New Rule. Its Effect: Less Science in Policymaking.',
 'The New Noma, Explained',
 'Unknown',
 'Unknown']

In [11]:
len(headline)

1324

In [12]:
headline=[n for n in headline if n!='Unknown']
len(headline)

1214

In [13]:
headline[:5]

['Former N.F.L. Cheerleaders’ Settlement Offer: $1 and a Meeting With Goodell',
 'E.P.A. to Unveil a New Rule. Its Effect: Less Science in Policymaking.',
 'The New Noma, Explained',
 'How a Bag of Texas Dirt  Became a Times Tradition',
 'Is School a Place for Self-Expression?']

In [16]:
from string import punctuation
def reprocessing(s):
    s=s.encode('utf8').decode('ascii','ignore')
    return "".join(c for c in s if c not in punctuation).lower()

text=[reprocessing(x) for x in headline]
text[:5]

['former nfl cheerleaders settlement offer 1 and a meeting with goodell',
 'epa to unveil a new rule its effect less science in policymaking',
 'the new noma explained',
 'how a bag of texas dirt  became a times tradition',
 'is school a place for selfexpression']

In [17]:
from keras_preprocessing.text import Tokenizer

t=Tokenizer()
t.fit_on_texts(text)

vocab_size=len(t.word_index)+1
print(vocab_size)

3494


In [19]:
sequences=list()

for line in text:
    encoded=t.texts_to_sequences([line])[0]
    for i in range(1,len(encoded)):
        sequence=encoded[:i+1]
        sequences.append(sequence)
    
print(len(sequences))
print(sequences[:11])

7803
[[99, 269], [99, 269, 371], [99, 269, 371, 1115], [99, 269, 371, 1115, 582], [99, 269, 371, 1115, 582, 52], [99, 269, 371, 1115, 582, 52, 7], [99, 269, 371, 1115, 582, 52, 7, 2], [99, 269, 371, 1115, 582, 52, 7, 2, 372], [99, 269, 371, 1115, 582, 52, 7, 2, 372, 10], [99, 269, 371, 1115, 582, 52, 7, 2, 372, 10, 1116], [100, 3]]


In [24]:
index_to_word={}
for key,value in t.word_index.items():
    index_to_word[value]=key
    
index_to_word[269]

'nfl'

In [25]:
max_len=max(len(i) for i in sequences)
print(max_len)

24


In [26]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

sequences=pad_sequences(sequences,maxlen=max_len,padding='pre')
print(sequences[:3])

[[   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0   99  269]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0   99  269  371]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0   99  269  371 1115]]


In [27]:
import numpy as np
sequences=np.array(sequences)

X=sequences[:,:-1]
y=sequences[:,-1]

In [28]:
print(X[:3])

[[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0  99]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0  99 269]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0  99 269 371]]


In [29]:
from tensorflow.keras.utils import to_categorical

y=to_categorical(y,num_classes=vocab_size)

In [30]:
print(y[:3])

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [31]:
from tensorflow.keras.layers import Embedding,Dense,LSTM
from tensorflow.keras.models import Sequential
model=Sequential()
model.add(Embedding(vocab_size,10,input_length=max_len-1))

model.add(LSTM(128))

model.add(Dense(vocab_size,activation='softmax'))
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])
model.fit(X,y,epochs=200)

Epoch 1/200
244/244 [==============================] - 9s 25ms/step - loss: 7.7483 - accuracy: 0.0259
Epoch 2/200
244/244 [==============================] - 6s 23ms/step - loss: 7.0773 - accuracy: 0.0328
Epoch 3/200
244/244 [==============================] - 6s 25ms/step - loss: 6.9709 - accuracy: 0.0316 0s - loss: 6.971
Epoch 4/200
244/244 [==============================] - 6s 23ms/step - loss: 6.8607 - accuracy: 0.0415
Epoch 5/200
244/244 [==============================] - 5s 22ms/step - loss: 6.6881 - accuracy: 0.0433
Epoch 6/200
244/244 [==============================] - 5s 22ms/step - loss: 6.4905 - accuracy: 0.0414
Epoch 7/200
244/244 [==============================] - 5s 22ms/step - loss: 6.3168 - accuracy: 0.0507
Epoch 8/200
244/244 [==============================] - 5s 22ms/step - loss: 6.1279 - accuracy: 0.0576
Epoch 9/200
244/244 [==============================] - 5s 22ms/step - loss: 5.8977 - accuracy: 0.0627
Epoch 10/200
244/244 [==============================] - 6s 23ms/s

244/244 [==============================] - 5s 21ms/step - loss: 1.0823 - accuracy: 0.7924
Epoch 80/200
244/244 [==============================] - 5s 21ms/step - loss: 1.0477 - accuracy: 0.7956
Epoch 81/200
244/244 [==============================] - 5s 21ms/step - loss: 1.0184 - accuracy: 0.8009
Epoch 82/200
244/244 [==============================] - 5s 21ms/step - loss: 1.0233 - accuracy: 0.8019
Epoch 83/200
244/244 [==============================] - 5s 21ms/step - loss: 0.9923 - accuracy: 0.8064
Epoch 84/200
244/244 [==============================] - 5s 21ms/step - loss: 0.9647 - accuracy: 0.8122
Epoch 85/200
244/244 [==============================] - 5s 21ms/step - loss: 0.9461 - accuracy: 0.8159
Epoch 86/200
244/244 [==============================] - 5s 21ms/step - loss: 0.9342 - accuracy: 0.8160
Epoch 87/200
244/244 [==============================] - 5s 21ms/step - loss: 0.8872 - accuracy: 0.8286
Epoch 88/200
244/244 [==============================] - 5s 21ms/step - loss: 0.8839 - 

244/244 [==============================] - 8s 33ms/step - loss: 0.2846 - accuracy: 0.9192
Epoch 156/200
244/244 [==============================] - 7s 27ms/step - loss: 0.2979 - accuracy: 0.9174
Epoch 157/200
244/244 [==============================] - 7s 27ms/step - loss: 0.2845 - accuracy: 0.9224
Epoch 158/200
244/244 [==============================] - 7s 27ms/step - loss: 0.2811 - accuracy: 0.9233
Epoch 159/200
244/244 [==============================] - 5s 21ms/step - loss: 0.2751 - accuracy: 0.9217
Epoch 160/200
244/244 [==============================] - 5s 21ms/step - loss: 0.2849 - accuracy: 0.9211 0s - loss: 0.2841 - accu
Epoch 161/200
244/244 [==============================] - 5s 21ms/step - loss: 0.2452 - accuracy: 0.9293
Epoch 162/200
244/244 [==============================] - 5s 21ms/step - loss: 0.2920 - accuracy: 0.9183
Epoch 163/200
244/244 [==============================] - 5s 21ms/step - loss: 0.2828 - accuracy: 0.9178
Epoch 164/200
244/244 [==============================

In [32]:
def sentence_generation(model,t,current_word,n):
    init_word=current_word
    sentence=''
    
    for _ in range(n):
        encoded=t.texts_to_sequences([current_word])[0]
        encoded=pad_sequences([encoded],maxlen=23,padding='pre')
        result=model.predict_classes(encoded,verbose=0)
        
        for word,index in t.word_index.items():
            if index==result:
                break
        current_word=current_word+' '+word
        sentence=sentence+' '+word
    sentence=init_word+sentence
    return sentence

In [ ]:
print(sentence_generation(model,t,'i',10))

In [36]:
print(sentence_generation(model,t,'how',10))

how to make facebook more accountable as jacket people may we
