## 통계

- #### 평균 확인

In [2]:
import numpy as np
a=[70,91,69,78,82]
avg=np.mean(a)
avg2=sum(a)/len(a)
print(avg,avg2)

78.0 78.0


- #### 분산과 표준편차의 차이 확인

In [3]:
a=[173,181,168,175,179]
b=[1.73,1.81,1.68,1.75,1.79]
print(np.var(a))
print(np.var(b))

20.959999999999997
0.0020960000000000037


In [4]:
print(np.std(a))
print(np.std(b))

4.578209256903839
0.04578209256903843


In [5]:
def standardize(x):
    return (x-np.mean(x))/np.std(x)

print(standardize(a))
print(standardize(b))

[-0.48053723  1.26687088 -1.5726673  -0.0436852   0.83001885]
[-0.48053723  1.26687088 -1.5726673  -0.0436852   0.83001885]


- #### 정규분포난수를 생성하고 평균과 표준편차 계산

In [10]:
n=np.random.randn(1000)

print(np.mean(n))
print(np.std(n))

0.03109140842747911
1.0027649314561


## 미분

- #### 2차함수계산

In [11]:
def f(x):
    return x**2+1

print(f(-2))
print(f(1))

5
2


- #### 미분

In [12]:
def df(a,h):
    return (f(a+h)-f(a))/h
for h in [1,1e-1,1e-2,1e-3]:
    print([h,df(0,h),df(1,h)])

[1, 1.0, 3.0]
[0.1, 0.10000000000000009, 2.0999999999999996]
[0.01, 0.009999999999998899, 2.010000000000023]
[0.001, 0.0009999999999177334, 2.0009999999999195]


## 행렬

- #### 행렬의 합과 차 계산

In [13]:
A=np.array([[1,2,3],[3,4,5]])
B=np.array([[3,4,5],[4,5,6]])

In [14]:
print(A+B)
print(A-B)

[[ 4  6  8]
 [ 7  9 11]]
[[-2 -2 -2]
 [-1 -1 -1]]


- #### 행렬의 곱 계산

In [15]:
B=([[3,4],[4,5],[5,6]])
print(A.dot(B))
print(A@B)

[[26 32]
 [50 62]]
[[26 32]
 [50 62]]


- #### 행렬의 역행렬

In [17]:
A=np.array([[2,5],[1,3]])
print(np.linalg.inv(A))

[[ 3. -5.]
 [-1.  2.]]


- #### 행렬식 계산

In [18]:
A=np.array([[2,5],[1,3]])
print(np.linalg.det(A))

B=np.array([[1,4,2],[3,-1,-2],[-3,1,3]])
print(np.linalg.det(B))

1.0
-13.0
